name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

env:
  WORKERS: 4
  BEE_API_URL: 'http://127.0.0.1:1633'

jobs:
  node-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      #- name: Auth to Github Package Docker Registry
      #  run: |
      #    echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin

      ## Try getting the node modules from cache, if failed npm ci
      - uses: actions/cache@v2
        id: cache-npm
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-${{ matrix.node }}-${{ env.cache-name }}-
            ${{ runner.OS }}-node-${{ matrix.node }}-
      - name: Install npm deps
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci && npm ci && npm install -g @fairdatasociety/fdp-play
      - name: Run FDP Play
        run: npx fdp-play start --workers $WORKERS -d
      - name: Run tests
        run: npm run test
